repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: requirements-txt-fixer
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.4
    hooks:
        # Run the linter.
        - id: ruff-check
          args: [ --fix ]
        # Run the formatter.
        - id: ruff-format
exclude: '(?i)\.(svg|key|png|stl|form)$'
